name: build
on:
  push:
    branches: [ gh-pages ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: 
      image: there4/markdown-resume:latest
    steps:
      - run: |
          cd /__w/cv/cv
          ls -al
          md2resume pdf -t readable kp-resume.md .
        name: Run in container