name: build
on:
  push:
    branches: [ gh-pages ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: 
      image: there4/markdown-resume:latest
    steps:
      - run: |
          md2resume pdf -t readable /__w/kp-resume.md /__w/
        name: Run in container