name: build
on:
  push:
    branches: [ gh-pages ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: 
      image: there4/markdown-resume:latest
        - ${ GITHUB_WORKSPACE }:/resume
    steps:
      - run: |
          md2resume pdf -t readable kp-resume.md .
        name: Run in container